### ISSUE TITLE
[Feature Request] SSH support

### ISSUE THREAD

**Issue by khuongduybui** [invm/noir#7]
Without SSH port forwarding support, it's virtually impossible to connect to any production database these days.

**Comment by invm** [comment]
Sounds reasonable, 
Currently busy on something else but I'll try to add support asap.

Thank you.

**Comment by invm** [comment]
@khuongduybui Sorry it took me some time, available in [1.1.0](https://github.com/invm/noir/releases/tag/v1.1.0).

**Comment by khuongduybui** [comment]
Thanks for getting it done. I'll give the new version a try tomorrow.


Duy K. Bui,
+1 571 239 6002

On Mon, May 27 2024 at 11:04 AM, Michael Ionov ***@***.******@***.***>> wrote:

@khuongduybui<https://github.com/khuongduybui> Sorry it took me some time, available in 1.1.0<https://github.com/invm/noir/releases/tag/v1.1.0>.
