### ISSUE TITLE
show bigint unsigned error

### ISSUE THREAD

**Issue by Caisin** [invm/noir#8]
show bigint unsigned error
![image](https://github.com/user-attachments/assets/141e93bb-5f14-4034-bb55-d72de5dc6b91)

**Comment by invm** [comment]
Thank you for reporting this issue, missed some types.

The fix is available in [1.1.2](https://github.com/invm/noir/releases/tag/v1.1.2).

Please let me know is further issues arise.

Take care.

**Comment by Caisin** [comment]
3q,this version(1.1.2)
bigint unsigned is ok
but tinyint is render error
maybe other unsigned number have same issue
![image](https://github.com/user-attachments/assets/4ce8ae21-2486-407f-bcdb-a0f1a195a090)

**Comment by invm** [comment]
You are right, went over all the numeric data types in MySQL and found other issues, building 1.1.3 at the moment.

Thank you very much again for reporting.
